types:
  Product:
    defaultOperations:
      collection_get:
        enabled: true
      collection_post:
        enabled: true
      item_get:
        enabled: true
      item_put:
        enabled: true
      item_delete:
        enabled: true
