types:
  Recipe:
    defaultOperations:
      collection_get:
        normalization_context:
          groups:
          - get_recipe
        denormalization_context:
          groups:
          - set_recipe
      collection_post:
        enabled: false
      item_get:
        normalization_context:
          groups:
          - get_recipe
        denormalization_context:
          groups:
          - set_recipe
      item_put:
        enabled: false
      item_delete:
        enabled: false