noinc_qris_ngview:
    resource: "@NoIncSimpleStorefrontViewBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
