security:
    access_decision_manager:
      strategy: unanimous
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: get_login
                check_path: post_login

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    access_control:
    - { path: ^/api, roles: ROLE_USER }
