security:
    access_decision_manager:
      strategy: unanimous
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:   ROLE_EDITOR
        ROLE_EDITOR:  ROLE_TEACHER
        ROLE_TEACHER: ROLE_USER
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: no_inc_SimpleStorefront_view_bundle_html_index
            logout:       true
            anonymous:    true
    access_control:
        - { path: ^/external, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_USER }
        - { path: ^/app, role: ROLE_USER }
        - { path: ^/app/dashboard, role: ROLE_ADMIN} # Force non-users to redirect to questions.
        - { path: ^/(login|forgot)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    providers:
        in_memory:
            memory:
                users:
                    ten1:
                        password: password
                        roles: 'ROLE_USER'
                    ten2:
                        password: password
                        roles: 'ROLE_USER'
#    firewalls:
#        oauth_api:
#          pattern: ^/oauth/v2/userinfo
#          fos_oauth: true
#          stateless: true
#          anonymous: true
#        oauth_token:
#          pattern:    ^/oauth/v2/token
#          security:   false
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                always_use_default_target_path: true
#                #default_target_path: /en/user
#                use_referer: true
#            logout:       true
#            anonymous:    true
#            switch_user: { role: ROLE_TENANT_ADMIN }
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

#    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/\w+/admin/, role: ROLE_USER }
