security:
    access_decision_manager:
      strategy: unanimous
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:   ROLE_EDITOR
        ROLE_EDITOR:  ROLE_TEACHER
        ROLE_TEACHER: ROLE_USER
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    firewalls:
        main:
            anonymous: ~
            http_basic: ~
            
#    access_control:
#        - { path: ^/api, role: ROLE_USER }
#        - { path: ^/app, role: ROLE_USER }
#        - { path: ^/, role: ROLE_USER }

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
