# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    app.translation.translation:
#        class: NoInc\Platform\CoreBundle\Translation
#        tags:
#            - { name: translation.loader, alias: bin }

#services:
#    security.access.voter:
#        class:  NoInc\SimpleStorefront\ApiBundle\Security\ACLVoter
#    security.access.acl:
#        class:  NoInc\SimpleStorefront\ApiBundle\EventListener\ACLListener
#        public: false
#        arguments:
#            - { service: security.access.voter }
#        tags:
#            - { name: kernel.event_listener, event: "kernel.view",  method: "onKernelView", priority: 12 }

