# Base pages
no_inc_flvs_view_bundle_html_index:
    path: /
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/base.html.twig'

# Error Pages
no_inc_flvs_view_bundle_html_error:
    path: /error.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/error.html.twig'

# Authentication related pages
no_inc_flvs_view_bundle_html_login:
    path: /auth/login.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/auth/login.html.twig'

no_inc_flvs_view_bundle_html_forgot:
    path: /auth/forgot.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/auth/forgot.html.twig'

no_inc_flvs_view_bundle_html_reset:
    path: /auth/reset.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/auth/reset.html.twig'

# Course page templates
no_inc_flvs_view_bundle_html_view_my_course:
    path: /courses/viewMyCourse.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/courses/viewMyCourse.html.twig'

no_inc_flvs_view_bundle_html_add_edit_course:
    path: /courses/addEditCourse.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/courses/addEditCourse.html.twig'

no_inc_flvs_view_bundle_html_all_courses:
    path: /courses/allCourses.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/courses/allCourses.html.twig'

no_inc_flvs_view_bundle_html_my_courses:
    path: /courses/myCourses.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/courses/myCourses.html.twig'

# Dashboard pages
no_inc_flvs_view_bundle_html_home:
    path: /dashboard/home.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/dashboard/home.html.twig'

# Partials used by dynamic pages
no_inc_flvs_view_bundle_html_base:
    path: /partials/base.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/base.html.twig'

no_inc_flvs_view_bundle_html_fab_menu:
    path: /partials/fabMenu.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/fabMenu.html.twig'

no_inc_flvs_view_bundle_html_math_help:
    path: /partials/mathHelp.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/mathHelp.html.twig'

no_inc_flvs_view_bundle_html_search_results:
    path: /partials/searchResults.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/searchResults.html.twig'

no_inc_flvs_view_bundle_html_sidebar:
    path: /partials/sidebar.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/sidebar.html.twig'

no_inc_flvs_view_bundle_html_topbar:
    path: /partials/topbar.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/topbar.html.twig'

no_inc_flvs_view_bundle_html_unauth_base:
    path: /partials/unauthBase.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/unauthBase.html.twig'

# Questions pages
no_inc_flvs_view_bundle_html_add_edit_question:
    path: /questions/addEditQuestion.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/questions/addEditQuestion.html.twig'

no_inc_flvs_view_bundle_html_questions:
    path: /questions/allQuestions.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/questions/allQuestions.html.twig'

# Users pages
no_inc_flvs_view_bundle_html_add_edit_user:
    path: /users/addEditUser.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/users/addEditUser.html.twig'

no_inc_flvs_view_bundle_html_all_users:
    path: /users/allUsers.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/users/allUsers.html.twig'

no_inc_flvs_view_bundle_html_my_profile:
    path: /users/myProfile.html
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/users/myProfile.html.twig'

# This catch all route allows deep linking into the angular app without
# Symfony generating 404 errors. All ui-router links in the app must be
# prefixed with /app/ for this to work :)
no_inc_flvs_view_bundle_catch_all:
    path: /app/{catch_all}
    requirements:
        catch_all: ".*"
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: '@NoIncFLVSViewBundle/partials/base.html.twig'
